import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from '@/app/context/ThemeProvider';
import Footer from "./components/Footer/page";

export const metadata: Metadata = {
  title: "Padshala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <ThemeProvider> */}
        {children}
        {/* </ThemeProvider> */}
        <Footer />
      </body>
    </html>
  );
}
